name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Pode ser ajustado para a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies and Build
        run: |
          npm install -g @angular/cli
          npm install
          ng build --configuration production

      - name: Run Tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Deploy to Hosting Service
        
        run: |
          ng deploy --base-href=/pipelines-demo/
          # Comandos para implantar no serviço de hospedagem
