name: Exemplo Pipeline

on:
  push:
    branches:
    - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalando dependencias
      run: npm install

    - name: Executanto testes
      run: npm run test:headless

    - name: Build
      run: npm run build:prod

    - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Diretório onde está a build do site
          user_name: "GitHub Actions" # Nome do usuário que realizará o commit
          user_email: "actions@users.noreply.github.com" # E-mail do usuário que realizará o commit
          publish_branch: gh-pages # Branch onde será publicado o site estático
          force_orphan: true # Força a criação de um novo histórico no branch gh-pages
