name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Pode ser ajustado para a branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies and Build
        run: |
          npm install -g @angular/cli
          npm install
          ng build --prod

      - name: Run Tests
        run: ng test --watch=false

      - name: Deploy to Hosting Service
        # Adapte esse passo para o seu serviço de hospedagem (exemplo: Firebase, AWS, Netlify, etc.)
        # Aqui está um exemplo para implantar em um serviço de hospedagem hipotético chamado "HostingService"
        run: |
          # Comandos para implantar no serviço de hospedagem
          # Exemplo: hosting-service deploy --project=my-project

# Adicione outras etapas conforme necessário (análise estática de código, notificações, etc.)
